# Generated by Django 5.0.4 on 2024-05-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_orderdetail_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
    ]
