# Generated by Django 5.0.4 on 2024-05-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_order_buyer_alter_order_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
