# Generated by Django 5.0.4 on 2024-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_product_store_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='buyer',
        ),
    ]
